#!/usr/bin/env bash

. public_lib.sh

for name in $(compgen -A function); do
	cat >"bin/$name" <<-EOF
	#!/usr/bin/env bash

	. public_lib.sh
	$name "\$@"
	EOF
done

cp -r scripts/. bin/

chmod -R +x bin/
