#!/usr/bin/env bash

. lib.sh
set -euo pipefail

# shellcheck disable=SC2016
readonly MAGIC_SRC='"$(dirname -- "$(realpath -- "$0")")/../"'

SCRIPT_TEMPLATE=$(
	cat <<EOF
#!/usr/bin/env bash

. $MAGIC_SRC/lib.sh
%s "\$@"
EOF
)
readonly SCRIPT_TEMPLATE

build() {
	mkdir -p bin

	cp -r scripts/. bin/
	for script in scripts/*; do
		local bin_script
		bin_script="bin/$(basename -- "$script")"
		sed -E 's/^\. (\w+)/\. _@STNL@_\1/g' "$script" \
			| sed "s#_@STNL@_#$MAGIC_SRC#g" > "$bin_script"
	done
	for name in "${PLIB_FUNCS[@]}"; do
		# shellcheck disable=SC2059
		printf "$SCRIPT_TEMPLATE" "$name" >"bin/$name"
	done

	chmod -R +x bin/
}

clean() {
	rm -rf bin/
}

main() {
	if ! [[ -v 1 ]]; then
		build
		return
	fi
	case $1 in
	build)
		build
		;;
	clean)
		clean
		;;
	esac
}

main "$@"
