#!/usr/bin/env bash

. lib.sh

main() {
	sudo ed -sq "$HOME/dotfiles/home.nix" >/dev/null <<- EOF
	/END PACKAGES/
	-a
	$@
	.
	wq
	EOF
	update_dot "Add package $* to home.nix" "$HOME/dotfiles/home.nix"
}

main "$@"
