#!/usr/bin/env bash

. lib.sh

main() {
	local home="$HOME/dotfiles/home.nix"
	as_owner "$home" ed -sq "$home" >/dev/null <<- EOF
	/END PACKAGES/
	-a
	$@
	.
	wq
	EOF
	update_dot "Add package $* to home.nix" "$home"
}

main "$@"
