#!/usr/bin/env python3

import argparse
import subprocess
from pathlib import Path

from ansi2html import Ansi2HTMLConverter
from weasyprint import HTML, CSS


def main():
    p = argparse.ArgumentParser()
    p.add_argument("input")
    p.add_argument("-o", "--output")
    a = p.parse_args()

    src = Path(a.input)
    dst = Path(a.output) if a.output else src.with_suffix(".pdf")

    ansi = subprocess.run(
        ["bat", "--theme=Monokai Extended Light", "--color=always", str(src)],
        check=True,
        stdout=subprocess.PIPE,
        text=True
    ).stdout

    content = Ansi2HTMLConverter(inline=True).convert(ansi, full=True)
    content = content.replace("color: #000000;", "color: #ffffff;")
    content = content.replace("color: #AAAAAA;", "color: #000000;")

    css = CSS(string="@page { margin: 0.10in }")
    HTML(string=content, base_url=".").write_pdf(str(dst), stylesheets=[css])

if __name__ == "__main__":
    main()
