#!/bin/sh

set -euo pipefail

PAT="$1"

xcode-select --install

git clone "https://BolunThompson@$PAT:github.com/BolunThompson/dotfiles.git"

curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm

cd dotfiles/

nix run nix-darwin --extra-experimental-features nix-command --extra-experimental-features flakes -- switch --flake . --show-trace
