#!/bin/sh

set -euo pipefail

sudo scutil --set LocalHostName "UCLAMac"

xcode-select --install || true

git clone "https://BolunThompson@github.com/BolunThompson/dotfiles.git"

curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm

cd dotfiles/

sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
sudo -i nix run nix-darwin/master#darwin-rebuild -- switch --flake ~/dotfiles/flake.nix

echo Use to upgrade: darwin-rebuild switch --flake ~/dotfiles/flake.nix
